export const FETCH_RENTALS = 'FETCH_RENTALS';
export const FETCH_RENTALS_SUCCESS = 'FETCH_RENTALS_SUCCESS';
export const FETCH_RENTALS_FAILURE = 'FETCH_RENTALS_FAILURE';

export const FETCH_USER_RENTALS = 'FETCH_USER_RENTALS';
export const FETCH_USER_RENTALS_SUCCESS = 'FETCH_USER_RENTALS_SUCCESS';
export const FETCH_USER_RENTALS_FAILURE = 'FETCH_USER_RENTALS_FAILURE';

export const FETCH_USER_BOOKINGS = 'FETCH_USER_BOOKINGS';
export const FETCH_USER_BOOKINGS_SUCCESS = 'FETCH_USER_BOOKINGS_SUCCESS';
export const FETCH_USER_BOOKINGS_FAILURE = 'FETCH_USER_BOOKINGS_FAILURE';

export const DELETE_USER_BOOKING = 'DELETE_USER_BOOKING';
export const DELETE_USER_BOOKING_SUCCESS = 'DELETE_USER_BOOKING_SUCCESS';
export const DELETE_USER_BOOKING_FAILURE = 'DELETE_USER_BOOKING_FAILURE';

export const FETCH_OWNER_BOOKINGS = 'FETCH_OWNER_BOOKINGS';
export const FETCH_OWNER_BOOKINGS_SUCCESS = 'FETCH_OWNER_BOOKINGS_SUCCESS';
export const FETCH_OWNER_BOOKINGS_FAILURE = 'FETCH_OWNER_BOOKINGS_FAILURE';

export const FETCH_ONE_RENTAL = 'FETCH_ONE_RENTAL';
export const FETCH_ONE_RENTAL_SUCCESS = 'FETCH_ONE_RENTAL_SUCCESS';
export const FETCH_ONE_RENTAL_FAILURE = 'FETCH_ONE_RENTAL_FAILURE';

export const CREATE_RENTAL = 'CREATE_RENTAL';
export const CREATE_RENTAL_SUCCESS = 'CREATE_RENTAL_SUCCESS';
export const CREATE_RENTAL_FAILURE = 'CREATE_RENTAL_FAILURE';

export const DELETE_RENTAL = 'DELETE_RENTAL';
export const DELETE_RENTAL_SUCCESS = 'DELETE_RENTAL_SUCCESS';
export const DELETE_RENTAL_FAILURE = 'DELETE_RENTAL_FAILURE';

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
