export const FETCH_RENTALS = 'FETCH_RENTALS';
export const FETCH_RENTALS_SUCCESS = 'FETCH_RENTALS_SUCCESS';
export const FETCH_RENTALS_FAILURE = 'FETCH_RENTALS_FAILURE';

export const FETCH_ONE_RENTAL = 'FETCH_ONE_RENTAL';
export const FETCH_ONE_RENTAL_SUCCESS = 'FETCH_ONE_RENTAL_SUCCESS';
export const FETCH_ONE_RENTAL_FAILURE = 'FETCH_ONE_RENTAL_FAILURE';

export const CREATE_RENTAL = 'CREATE_RENTAL';
export const CREATE_RENTAL_SUCCESS = 'CREATE_RENTAL_SUCCESS';
export const CREATE_RENTAL_FAILURE = 'CREATE_RENTAL_FAILURE';
