module.exports = {
  MONGODB_URI: process.env.MONGODB_URI,
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
  CLOUDINARY_NAME: process.env.CLOUDINARY_NAME,
  CLOUNDINARY_KEY: process.env.CLOUDINARY_KEY,
  CLOUNDINARY_SECRET: process.env.CLOUDINARY_SECRET,
};
